apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: nginx
data:
  nginx.conf: |
    server {
      listen 80;
      server_name default;
      location / {
        return 200 "Cats and Dogs Review App";
      }
      location /cats {
        return 200 "About Cats";
      }
      location /dogs {
        return 200 "About Dogs";
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cdr-dep
  namespace: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-cdr-dep
  template:
    metadata:
      labels:
        app: nginx-cdr-dep
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 25
            periodSeconds: 10
          volumeMounts:
          - name: config-volume
            mountPath: /etc/nginx/conf.d/nginx.conf
            subPath: nginx.conf 
      volumes:
      - name: config-volume
        configMap:
          name: nginx-configmap
          items:
          - key: nginx.conf
            path: nginx.conf

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: nginx
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80