apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: nginx
data:
  default.conf: |
    server {
      listen 80;
      server_name default;
      location / {
        return 200 "Cats and Dogs Review App";
      }
      location /cats {
        return 200 "About Cats";
      }
      location /dogs {
        return 200 "About Dogs";
      }
    }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-cdr
  namespace: nginx
spec:
  replicas: 2
  serviceName: nginx-cdr
  selector:
    matchLabels:
      app: nginx-cdr
  template:
    metadata:
      labels:
        app: nginx-cdr
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config
            defaultMode: 420
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 25
            periodSeconds: 10
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: data-volume
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: data-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
       
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx-service
  type: ClusterIP
